[package]
name = "pbkdf2sha512"
version = "1.0.0"
description = "PBKDF2-HMAC-SHA512 implementation for Motoko"
repository = "https://github.com/nirvana369/pbkdf2_sha512"
keywords = [ "pbkdf2", "hmac", "sha512", "hash", "password" ]
license = "MIT"

[dependencies]
test = "2.0.0"
bench = "1.0.0"